name: CI

on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Node ${{ matrix.node }} and ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16, 18, 20]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    # https://github.com/nodejs/node-gyp#installation
    - name: Use Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{ matrix.node }}
        registry-url: 'https://registry.npmjs.org'
        check-latest: true
    - name: Install Dependencies
      run: npm i global node-gyp && npm i --frozen-lockfile --legacy-peer-deps --force
    - name: Build
      run: npm run build
    - name: Maybe Release
      if: matrix.os == 'ubuntu-latest' && matrix.node == 20 && github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
